name: Build and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - src/**
      - content/**
      - public/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 19.x
      uses: actions/setup-node@v3
      with:
        node-version: 19.x
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build production website
      run: yarn astro build

    - name: Deploy on dedicated
      uses: garygrossgarten/github-action-scp@release
      with:
        local: dist
        remote: website/public/
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        privateKey: ${{ secrets.PRIVATE_KEY}}

