name: Notify new blogpost

on:
  push:
    branches: [ main ]
    paths:
      - content/**

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Twitter notification
      uses: ethomson/send-tweet-action@v1
      with:
        status: "I published a new article on my blog https://clauzier.dev/"
        consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
        access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

    - name: Discord notification (FR)
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_FR }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'Un nouvel article de blog a été publié sur https://clauzier.dev/'

    - name: Discord notification (EN)
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_EN }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'A new blog article has been published on https://clauzier.dev/'